DATE_INPUT_FORMATS = (
    '%Y-%m-%d',
    '%Y %m %d',
    '%Y/%m/%d',
    '%Y.%m.%d',
    '%m/%d/%Y',
    '%m %d %Y',
    '%m-%d-%Y',
    '%m.%d.%Y',
    '%d/%m/%Y',
    '%d %m %Y',
    '%d.%m.%Y',
    '%d-%m-%Y',
    '%m/%d/%y',
    '%b %d %Y',
    '%b %d, %Y',
    '%d %b %Y',
    '%d %b, %Y',
    '%B %d %Y',
    '%B %d, %Y',
    '%d %B %Y',
    '%d %B, %Y'
)